In [1]:
import numpy as np

In [8]:
arr_1d=np.array([1,2,3,4,5])
print("1d_array",arr_1d)

arr_2d=np.array([[1,2,3],[4,5,6]])
print("2d_array=",arr_2d)

1d_array [1 2 3 4 5]
2d_array= [[1 2 3]
 [4 5 6]]


## List vs numpy

In [11]:
py_list=[1,2,3]
print("pyhton list multiplication",py_list*2)

#numpy as list
np_array=np.array([1,2,3,4])
print(np_array*2)

pyhton list multiplication [1, 2, 3, 1, 2, 3]
[2 4 6 8]


# Write a Python program to convert a list of numeric value into a one-dimensional


In [14]:
list=[12.23, 13.32, 100, 36.32]
arr_1d=np.array(list)
arr_1d

array([ 12.23,  13.32, 100.  ,  36.32])

# Create a 3x3 matrix with values ranging from 2 to 10.

In [44]:
mat=np.arange(2,11).reshape(3,3)
mat

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

# Write a Python program to create a null vector of size 10 and update sixth value to 11.

In [23]:
arr1=np.zeros(10)
arr1[6]=11
arr1

array([ 0.,  0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.])

# Write a Python program to reverse an array (first element becomes last).


In [29]:
arr_1d=np.array([12 ,13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37])
a=arr_1d[::-1]
a

array([37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21,
       20, 19, 18, 17, 16, 15, 14, 13, 12])

# Write a Python program to create a 2d array with 1 on the border and 0 inside.

In [36]:
arr_2d=np.ones((5,5))
arr_2d[1:4,1:4]=0
arr_2d

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

# Write a Python program to add a border (filled with 0's) around an existing array.

In [62]:
arr_2d=np.ones((3,3))
p = np.pad(arr_2d, pad_width=1, mode='constant')
p



array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

#Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.

In [81]:
arr=np.zeros((8,8))
arr[::2,1::2]=1
arr[1::2,::2]=1
print(arr)

# indices
arr_2d=np.indices((8,8)).sum(axis=0)%2
arr_2d

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

# Write a Python program to convert a list and tuple into arrays.

In [84]:
list=[1,2,3,4,5,6,7,8]
tu=((1,2,3,4),(5,6,7,8))
arr_1=np.array(list)
arr_2=np.array(tu)
print(arr_1,arr_2)

[1 2 3 4 5 6 7 8] [[1 2 3 4]
 [5 6 7 8]]


# Write a Python program to append values to the end of an array.

In [95]:
arr_1=[10, 20, 30]
arrk=np.append(arr_1,([40,50,60,70,80,90]))
arrk

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

# Write a Python program to find the real and imaginary parts of an array of complex


In [97]:
arr=np.array([1.00000000+0.j ,0.70710678+0.70710678j])
print(np.real(arr))
print(np.imag(arr))

[1.         0.70710678]
[0.         0.70710678]


# Write a Python program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements.

In [104]:
arr=np.array([1,2,3])
print("Size of the array: ",arr.size)
print("Length of one array element in bytes: ",arr.itemsize)
print("Total bytes consumed by the elements of the array: ",arr.nbytes)

Size of the array:  3
Length of one array element in bytes:  8
Total bytes consumed by the elements of the array:  24


# Write a Python program to find common values between two arrays.

In [108]:
arr1=[0,10,20,40,60]
arr2=[10,30,40,50,60,70,90]
arr3=np.intersect1d(arr1,arr2)
arr3

array([10, 40, 60])

# Write a Python program to find the set difference of two arrays. The set difference will return the sorted, unique values in array1 that are not in array2.

In [115]:
arr1=np.array([ 0,10,20,40,60,80])
arr2=np.array([10,30,40,50,70,90])
arr5 = np.setdiff1d(arr1, arr2)
print(np.sort(arr5))

[ 0 20 60 80]


# Write a Python program to find the set exclusive-or of two arrays. Set exclusive-or will return the  sorted, unique values that are in only one (not both) of the input arrays.

In [121]:
arr1=np.array([ 0,10,20,40,60,80])
arr2=np.array([10, 30, 40, 50, 70])
arr5=np.setdiff1d(arr1,arr2)
arr6=np.setdiff1d(arr2,arr1)
arr7=np.append(arr5,arr6)
print(np.sort(arr7))


[ 0 20 30 50 60 70 80]


# Write a Python program compare two arrays using numpy.

In [125]:
arr_1=np.array([1,2])
arr_2=np.array([4,5])

arrg=arr_1>arr_2
print(arrk)

arrgE=arr_1>=arr_2
print(arrgE)


arrl=arr_1<arr_2
print(arrl)

arrlg=arr_1<=arr_2
print(arrlg)


[False False]
[False False]
[ True  True]
[ True  True]


In [127]:
arr_1=np.array([1,2,3,4,5])
np.savetxt('my_array.txt', arr, fmt='%d', delimiter=',')

print("Array saved to 'my_array.txt'")

Array saved to 'my_array.txt'


# Write a Python program to create a contiguous flattened array.

In [132]:
flat=np.array([[10,20,30],[20,40,50]])
arrl=flat.flatten()
print(arrl)

[10 20 30 20 40 50]


# Write a Python program to change the data type of an array.

In [134]:
arrk=np.array([[2,4,6],[6,8,10]])
arr=arrk.astype(np.float64)
print(arr)

[[ 2.  4.  6.]
 [ 6.  8. 10.]]


# 18. Write a Python program to create a 3-D array with ones on a diagonal and zeros

In [139]:
d = np.array([1, 1, 1])
matrix = np.diag(d)

print(matrix)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


# Write a Python program to create an array which looks like below array.

In [154]:
import numpy as np


arr = np.zeros((4, 3))

for i in range(1,4):
    for j in range(min(i , 4)):
        arr[i][j] = 1


print(arr)

[[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


# Write a Python program to concatenate two 2-dimensional arrays.

In [161]:
arr=np.array([[0, 1, 3], [5, 7, 9]])
arr2=np.array([[0, 2, 4], [6, 8, 10]])
result = np.concatenate((arr, arr2), axis=1)
result



array([[ 0,  1,  3,  0,  2,  4],
       [ 5,  7,  9,  6,  8, 10]])

# Write a Python program to make an array immutable (read-only).

In [163]:
arr=np.array([1,2,3,4,5,6])
arr.flags.writeable=False
arr[0]=10

ValueError: assignment destination is read-only

# Write a Python program to create an array of (3, 4) shape, multiply every element value by 3 and display the new array.

In [165]:
arr=np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])
arr1=arr*3
arr1

array([[ 0,  3,  6,  9],
       [12, 15, 18, 21],
       [24, 27, 30, 33]])

# Write a Python program to convert a NumPy array into Python list structure.

In [167]:
arr=np.array([[0,1],[2,3],[4,5]])
lst=arr.tolist()
lst

[[0, 1], [2, 3], [4, 5]]

# Write a Python program to convert a NumPy array into Python list structure.

In [170]:
arr=np.array([ 0.26153123 ,0.52760141, 0.5718299, 0.5927067, 0.7831874, 0.69746349,
0.35399976, 0.99469633, 0.0694458, 0.54711478])

arr1=np.round(arr,3)
lst=arr1.tolist()
lst

[0.262, 0.528, 0.572, 0.593, 0.783, 0.697, 0.354, 0.995, 0.069, 0.547]

# Write a Python program to suppresses the use of scientific notation for small.

In [ ]:
arr=np.array([1.60000000e-10, 1.60000000e+00, 1.20000000e+03, 2.35000000e-01])
arr1=np.round(arr,3)
lst=arr1.tolist()
lst

[0.0, 1.6, 1200.0, 0.235]

# Write a Python program to how to add an extra column to an numpy array.

In [174]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
new_col=np.array([10,20])
res=np.column_stack((arr,new_col))
res

array([[ 1,  2,  3,  4, 10],
       [ 5,  6,  7,  8, 20]])

# Write a Python program to remove specific elements in a numpy array.

In [175]:
arr=np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
arr_new = np.delete(arr, [0, 3, 4])
arr_new

array([ 20,  30,  60,  70,  80,  90, 100])